run:
  timeout: 5s

linters-settings:
  lll:
    line-length: 170
  nlreturn:
    block-size: 2

linters:
  enable-all: true
  disable:
    - depguard
    - gci
    - varnamelen
    - exhaustruct
    - errcheck
    - dupl
